apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-case-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-case-app
  template:
    metadata:
      labels:
        app: devops-case-app
    spec:
      containers:
      - name: app
        image: ghcr.io/bthngcr/devops-case-app:b42f468917ccb39516a68cafe66d7754c3ae1a0f
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"    # TODO cpu/mem değiştirisem ne olur nasıl update edebilirim?
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port : 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: ghcr-secret